stages:
    - build
    - test
    - deploy

build:
  stage: build
  script: 
    - echo "BUILD"
    - skillbox_app.yml



test:
  stage: test
  script: echo "TEST"

deploy:
  stage: deploy
  script: echo "DEPLOY"
