stages:
    - test
    - build
    - deploy

test:
  stage: test
  script: 
    - echo "TEST"
    - ./run-tests.sh
  allow_failure: true

build:
  before_script:
    - export ANSIBLE_CONFIG=./ansible.cfg
    - eval $(ssh-agent -s)
    #- ssh-add -K ~/.ssh/id_rsa
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    
  script:
    - echo "BUILD"
    - ansible-playbook -i inventory /ansible/skillbox_app.yml
  allow_failure: true 
  

deploy:
  stage: deploy
  script: echo "DEPLOY"
