stages:
    - build
    - test
    - deploy

variables:
  DOCKER_IMAGE_RELEASE_VERSION: "v1"  # Initial release 

Docker Build:
  stage: build
  image: docker:24.0.5
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  services:
  - docker:24.0.5-dind

  script:
    - >
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        export DOCKER_IMAGE_RELEASE_VERSION="v$(($(echo $DOCKER_IMAGE_RELEASE_VERSION | tr -d 'v') + 1))"
        export DOCKER_IMAGE_TAG="${DOCKER_IMAGE_RELEASE_VERSION}"
      else
        export DOCKER_IMAGE_TAG="latest"
      fi
    - echo "DOCKER_IMAGE_RELEASE_VERSION: $DOCKER_IMAGE_RELEASE_VERSION"
    - echo "DOCKER_IMAGE_TAG: $DOCKER_IMAGE_TAG"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_BRANCH}:${DOCKER_IMAGE_TAG} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_BRANCH}:${DOCKER_IMAGE_TAG}  
  tags: 
    - hp_runner 


test:
  stage: test
  image: docker:24.0.5
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
  - docker:24.0.5-dind
  script:
    - docker run -v $(pwd):/tests golang:1.16.6-alpine3.14 /tests/scripts/test_in_docker.sh
    
  tags: 
    - hp_runner     

Deploy_to_test_env:
  stage: deploy 
  needs:
    - test 
  rules:
    - if: $CI_COMMIT_BRANCH == "uat"  
  before_script:
    - export ANSIBLE_CONFIG=./ansible.cfg
    - 'command -v ssh-agent >/dev/null || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apk add --no-cache aws-cli python3 py3-pip
    - pip3 install boto3 botocore

  image:
    name: uhligit/ansible:2.1.0-3-g46e41b3

  script:
    - echo "Deploy to test env"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - ansible-inventory --graph -i ansible/service.aws_ec2.yml
    - ansible-playbook ansible/skillbox_app.yml -i ansible/service.aws_ec2.yml --extra-vars "ci_commit_branch=$CI_COMMIT_BRANCH"
  tags: 
    - hp_runner   
  
Deploy_to_prod:
  stage: deploy 
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  
      when: manual
  before_script:
    - export ANSIBLE_CONFIG=./ansible.cfg
    - 'command -v ssh-agent >/dev/null || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apk add --no-cache aws-cli python3 py3-pip
    - pip3 install boto3 botocore


  image:
    name: uhligit/ansible:2.1.0-3-g46e41b3

  script:
    - echo "Deploy to prod env"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - ansible-inventory --graph -i ansible/service.aws_ec2.yml
    - ansible-playbook ansible/skillbox_app.yml -i ansible/service.aws_ec2.yml --extra-vars "ci_commit_branch=$CI_COMMIT_BRANCH"
    - ansible-playbook ansible/skillbox_app.yml -i ansible/service.aws_ec2.yml --extra-vars "ci_commit_branch=$CI_COMMIT_BRANCH release_version=$DOCKER_IMAGE_RELEASE_VERSION"
  tags: 
    - hp_runner   


