stages:
    - test
    - build
    - deploy

test:
  stage: test
  script: 
    - echo "TEST"
    - "./run-tests.sh"
  allow_failure: true

  
build:
  stage: build
  script: 
    - echo "BUILD"
    - ansible-playbook ansible/skillbox_app.yml
  allow_failure: true  


deploy:
  stage: deploy
  script: echo "DEPLOY"
