stages:
    - build
    - test
    - deploy


Docker Build:
  stage: build
  image: docker:20.10.16
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  services:
  - docker:20.10.16-dind

  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} . 
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
    - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
  tags: 
    - hp_runner 


test:
  stage: test
  image: docker:20.10.16
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
  - docker:20.10.16-dind
  script:
    - docker run -v $(pwd):/tests golang:1.16.6-alpine3.14 /tests/scripts/test_in_docker.sh
    
  tags: 
    - hp_runner     

Deploy_to_test_env:
  stage: deploy 
  needs:
    - test 
  rules:
    - if: $CI_COMMIT_BRANCH == "uat"  
  before_script:
    - export ANSIBLE_CONFIG=./ansible.cfg
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  image:
    name: uhligit/ansible:2.1.0-3-g46e41b3

  script:
    - echo "Deploy to test env"
    - ansible-inventory --graph -i ./aws_ec2.yml
    - ansible-playbook ansible/skillbox_app.yml -i ./aws_ec2.yml
  tags: 
    - hp_runner   
  
Deploy_to_prod:
  stage: deploy 
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  
      when: manual
  before_script:
    - export ANSIBLE_CONFIG=./ansible.cfg
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  image:
    name: uhligit/ansible:2.1.0-3-g46e41b3

  script:
    - echo "Deploy to prod env"
    - ansible all -m ping -i ./inventory 
    - ansible-playbook ansible/skillbox_app.yml 
  tags: 
    - hp_runner   


