stages:
    - test
    - build
    - deploy

test:
  stage: test
  image:
    name: ubuntu:focal
  script: 
    - echo "TEST"
    - ./run-tests.sh
  allow_failure: true

build:
  stage: build
  before_script:
    - export ANSIBLE_CONFIG=./ansible.cfg
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  image:
    name: uhligit/ansible:2.1.0-3-g46e41b3
    
  script:
    - echo "BUILD"
    - ansible-playbook ansible/skillbox_app.yml -i ./inventory --private-key $SSH_PRIVATE_KEY
#  tags: 
#    - vm_aws_docker_runner  
  allow_failure: true 
  

deploy:
  stage: deploy
  script: echo "DEPLOY"
