stages:
    - test
    - build
    - deploy

test:
  stage: test
  script: 
    - echo "TEST"
    - run-tests.sh

build:
  stage: build
  script: 
    - echo "BUILD"
    - skillbox_app.yml


deploy:
  stage: deploy
  script: echo "DEPLOY"
