stages:
    - test
    - build
    - deploy

test:
  stage: test
  script: 
    - echo "TEST"
    - ./run-tests.sh
  allow_failure: true

  
build:
  stage: build
  script: 
    - echo "BUILD"
    - skillbox_app.yml


deploy:
  stage: deploy
  script: echo "DEPLOY"
