stages:
    - test
    - build
    - deploy

test:
  stage: test
  script: 
    - echo "TEST"
    - ./run-tests.sh
  allow_failure: true

build:
#  before_script:
#    - export ANSIBLE_CONFIG=./ansible.cfg
#    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
#    - eval $(ssh-agent -s)
#    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
  image:
    name: devupsen/ansible:6.5.1
    
  script:
    - echo "BUILD"
    - ansible-playbook /ansible/skillbox_app.yml -i ./inventory --private-key="SSH_PRIVATE_KEY"
  allow_failure: true 
  

deploy:
  stage: deploy
  script: echo "DEPLOY"
