version: '3.1'

services:
  app:
    image: registry.gitlab.com/miklashevich.a/service/${CI_COMMIT_BRANCH}/skillbox_app:latest
    container_name: app
    restart: always
    ports:
      - '8080:8080'

