plugin: amazon.aws.aws_ec2
aws_access_key: $AWS_ACCESS_KEY_ID
aws_secret_key: $AWS_SECRET_ACCESS_KEY

keyed_groups:
  - key: tags.Name
filters:
  instance-state-name: running
compose:
ansible_host: public_ip_address
