---
- hosts:
    - _App_Server_in_ASG
  become: true
  become_user: root
  vars:
    repository: https://gitlab.com/miklashevich.a/service.git
    app_path: diploma
    version_key: "app/release_version"

  tasks:
    - name: "Clone the repository"
      git:
        repo: "{{ repository }}"
        dest: "{{ app_path }}"

    - name: "Copy unit file to app_server"
      template:
        src: skillbox-app.service.j2
        dest: /etc/systemd/system/skillbox-app.service
        mode: 0644

    - name: "Start a service with systemd"
      systemd:
        daemon_reload: true
        name: skillbox-app.service
        state: started

    - name: "Enable app service"
      systemd:
        name: skillbox-app.service
        state: started

    - name: "Load current version from Consul"
      command: "consul kv get {{ version_key }}"
      register: current_version
      ignore_errors: yes
      when: "'main' in ci_commit_branch"

    - name: "Set initial version if not found"
      set_fact:
        app_version: "v1"
      ignore_errors: yes  
      when: current_version is not defined or current_version | length == 0 and 'main' in ci_commit_branch

    - name: "Update version for main branch"
      set_fact:
        app_version: "v{{ current_version | int + 1 }}"
      ignore_errors: yes  
      when: "'main' in ci_commit_branch"

    - name: "Store updated version in Consul"
      command: "consul kv put {{ version_key }} {{ app_version }}"
      ignore_errors: yes
      when: "'main' in ci_commit_branch"
